### PR TITLE
fix: fix map-components angular tests

### PR DESCRIPTION
**Pull request by nick-romano**
This pr fixes the angular tests in the map components package.

It was required to turn off source maps on the test build, otherwise a memory overflow would occur.

I isolated the issue to the `defineCustomElements` function. will discuss with the components team to see if it is something we could improve, and there are already some efforts in improving the bundle size of lazy loaded components.

The source map issue only occurs on the test build, so it could also have something to do with the "@angular-devkit/build-angular:karma" builder

### CODE REVIEW

**Comment by andygup** [comment]
I'll look at it again in the morning. When I just tried to run the spec  I got the following error.

image

**Comment by nick-romano** [comment]
> @nick-romano I reinstalled fresh this morning and I'm getting the same error.

@andy are you using the `next` branch?

**Comment by nick-romano** [comment]
wonder if having @angular/cli globally covers those deps? anyway- added the jasmine/karma deps

**Comment by andygup** [comment]
> are you using the nr/angular-tests branch?

Yep, I'm following the workflow of only installing that subdirectory and not using any globals or yarn. I'll give it another go.

**Comment by andygup** [comment]
Also, we should remove the `npm: <version>" designation. It will throw errors:

image

**Review by andygup — APPROVED** [review]
I chatted with @nick-romano. LGTM! 🚀  He's going to modify  `expect(compiled.querySelector('arcgis-map')).toBeDefined();` so it can't throw a false positive.

**Pull request merged**
