### PR TITLE
4.29

### PR DESCRIPTION
**Pull request by nick-romano**
This PR will:
- update all the @arcgis packages to use `~4.29.0`
- merge the next branch into main, with a lot changes from #11  PR, and #15 

We should double check each template before merging this one!

Ready for review

TODO:
  - [x] merge charts PR (#15)

### CODE REVIEW

**Comment by nick-romano** [comment]
calling all testers! Please work through each sample and report any issues! so far so good on my end.

**Comment by jimmychen97** [comment]
Charts templates testing:
- Was able to run each template in isolation (downloaded folder) with no console errors.

**Comment by andygup** [comment]
@nick-romano I'm probably not going to be able to finish testing before go-live. If you need to, go ahead and merge since both you and @jimmychen97 had successful test runs. If I find something after merge, I'll create a PR or issue. Nice job, all!

**Comment by bsvensson** [comment]
> @nick-romano I'm probably not going to be able to finish testing before go-live. If you need to, go ahead and merge since both you and @jimmychen97 had successful test runs. If I find something after merge, I'll create a PR or issue. Nice job, all!

Ditto. I think it's "good enough" to go live!

**Comment by nick-romano** [comment]
A few small issues(not show stoppers):
- Outdated package here:
https://github.com/Esri/arcgis-maps-sdk-javascript-samples-beta/blob/4a3dab68f43805bdd0ff707b12c65ee32bc9f4ab/packages/coding-components/templates/amd-script-tag/index.html#L28-L29
- calcite components would ideally have a hat in the version number, i.e. `^2.4.0` instead of `2.4.0`
- the charts component vite build doesn't work quite right ( components don't render), dev works fine
- Angular copy in charts component doesn't work in monorepo

All that said, I'm going to merge this one in the essence of time, and not seeing any show stoppers.

**Comment by nick-romano** [comment]
But please test things out / review when you find time!

**Pull request merged**
