### PR TITLE
chore: update links in READMEs

### PR DESCRIPTION
**Pull request by omarkawach**
Updating the READMEs to 
- link to online IDEs 
- link back to this repo

### CODE REVIEW

**Review by sagewall — APPROVED** [review]
I like the Icons 😃 A little hesitant about the StackBlitz links with the current bug but we can always change them.

**Comment by andygup** [comment]
Hmmm, I'm getting a variety of errors on StackBlitz with two samples that I tested at random. Here's the map-components Angular sample:

image

And, the map-components Vite sample:

image

**Comment by sagewall** [comment]
The [Vite](https://stackblitz.com/github/Esri/arcgis-maps-sdk-javascript-samples-beta/tree/main/packages/map-components/templates/vite) one worked for me twice in a row but the [angular one](https://stackblitz.com/github/Esri/arcgis-maps-sdk-javascript-samples-beta/tree/main/packages/coding-components/templates/angular) crashed twice in a row with the same error an Andy

**Comment by sagewall** [comment]
We should probably hold off on merging until we figure out the SB issue

**Comment by andygup** [comment]
> We should probably hold off on merging until we figure out the SB issue

👍

**Comment by omarkawach** [comment]
@andygup 

> Angular sample

Updating Angular might solve this. I see now that the Angular sample was throwing errors. Something to do with zone.js. I made a PR.

> Vite sample

I'm only seeing a NetworkError when I open the Vite sample in Edge or Firefox. No problems in Chrome.

image

image

**Comment by andygup** [comment]
> Updating Angular might solve this. I see now that the Angular sample was throwing errors. Something to do with zone.js. I made a PR.

Did you test the Angular update against a private repo? That's the best way to know if updating works. I saw the very odd console message: `Error: NG0908: In this configuration Angular requires Zone.js`.

> Firefox network errors

I tried it multiple times and got the same error. I'll try on my home laptop.

**Comment by andygup** [comment]
> Dunno if you noticed but the preconfigured Angular and React templates in StackBlitz do not come with a terminal.

Sure did, and I think you mentioned that last, as well. I don't get it.

> It might be time to update the samples to be CDN assets first instead of local.

+1

**Comment by omarkawach** [comment]
Closing this PR. We can revisit in the future for jsapi-resources.

**Pull request closed without merging**
